//
//  LoginPresenter.swift
//  taskManager
//
//  Created by Давид Тоноян  on 22.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ILoginPresentationLogic {

	/// Функция сообщает презентеру, что нужно отобразить.
	/// - Parameter response: Ответ интерактора от которого зависит отображение.
	func present(response: LoginModel.Response)
}

final class LoginPresenter: ILoginPresentationLogic {
	weak var viewController: ILoginDisplayLogic?

	func present(response: LoginModel.Response) {
		let viewModel: LoginModel.ViewModel = response.isLoginSuccessed
			? .success
		: .failure(L10n.Authorization.Error.message)
		viewController?.renderData(with: viewModel)
	}
}
