//
//  LoginWorker.swift
//  taskManager
//
//  Created by Давид Тоноян  on 22.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

struct Login {
	let rawValue: String

	init(rawValue: String) {
		self.rawValue = rawValue
	}
}

struct Password {
	let rawValue: String

	init(rawValue: String) {
		self.rawValue = rawValue
	}
}

protocol ILoginWorker {
	func login(login: Login, password: Password) -> Bool
}

final class LoginWorker: ILoginWorker {

	/// Функция валидирует логин и пароль.
	/// - Parameters:
	///   - login: Логин.
	///   - password: Пароль.
	/// - Returns: Результат валидации.
	func login(login: Login, password: Password) -> Bool {
		return login.rawValue == "Admin" && password.rawValue == "pa$$32!"
	}
}
