//
//  LoginInteractor.swift
//  taskManager
//
//  Created by Давид Тоноян  on 22.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ILoginBusinessLogic {

	/// Функция логина, отправляет запрос валидации.
	/// - Parameter request: Запрос с данными для логина.
	func login(request: LoginModel.Request)
}

final class LoginInteractor: ILoginBusinessLogic {
	private let presenter: ILoginPresentationLogic?
	private let worker: ILoginWorker

	init(worker: ILoginWorker, presenter: ILoginPresentationLogic) {
		self.worker = worker
		self.presenter = presenter
	}

	func login(request: LoginModel.Request) {
		let login = Login(rawValue: request.login)
		let pass = Password(rawValue: request.password)
		let result = worker.login(login: login, password: pass)
		let response = LoginModel.Response(isLoginSuccessed: result)
		presenter?.present(response: response)
	}
}
