//
//  LoginWorker.swift
//  taskManager
//
//  Created by Давид Тоноян  on 22.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class LoginWorker {
	
	/// Функция валидирует логин и пароль
	/// - Parameters:
	///   - login: Логин
	///   - password: Пароль
	/// - Returns: Результат валидации
	func login(login: String, password: String) -> Bool{
		return login == "Admin" && password == "pa$$32!"
	}
}
