//
//  LoginPresenter.swift
//  taskManager
//
//  Created by Давид Тоноян  on 22.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic {
	
	///  Функция сообщает презентеру, что нужно отобразить
	/// - Parameter response: Ответ интерактора от которого зависит отображение
	func presentSomething(response: LoginModel.Something.Response)
}

final class LoginPresenter: LoginPresentationLogic {
	weak var viewController: LoginDisplayLogic?

	// MARK: Do something

	func presentSomething(response: LoginModel.Something.Response) {
		if response.isLoginSuccessed {
			viewController?.processLogin()
		} else {
			viewController?.displayError()
		}
	}
}
