//
//  LoginViewController.swift
//  taskManager
//
//  Created by Давид Тоноян  on 22.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginDisplayLogic: AnyObject {
	func displayError()
	func processLogin(viewModel: Login.Something.ViewModel)
}

class LoginViewController: UIViewController, LoginDisplayLogic {
	@IBOutlet
	weak var loginTextField: UITextField!
	@IBOutlet
	weak var passwordTextField: UITextField!

	var interactor: LoginBusinessLogic?
	var router: (NSObjectProtocol & LoginRoutingLogic)?

	// MARK: Object lifecycle

	override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
		super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
		setup()
	}

	required init?(coder aDecoder: NSCoder) {
		super.init(coder: aDecoder)
		setup()
	}

	// MARK: Setup

	private func setup() {
		let viewController = self
		let interactor = LoginInteractor()
		let presenter = LoginPresenter()
		let router = LoginRouter()
		viewController.interactor = interactor
		viewController.router = router
		interactor.presenter = presenter
		presenter.viewController = viewController
		router.viewController = viewController
	}

	// MARK: View lifecycle

	override func viewDidLoad() {
		super.viewDidLoad()
	}

	// MARK: Do something
	
	func displayError() {
//		router?.showError()
		processLogin(viewModel: .init(greeting: ""))
	}
	
	func processLogin(viewModel: Login.Something.ViewModel) {
		print(viewModel.greeting)
		router?.navigateToMainScreen()
	}

	@IBAction
	func loginButtonTapped(_ sender: UIButton) {
		guard let loginText = loginTextField.text,
		      let passwordText = passwordTextField.text
		else {
			return
		}

		let request = Login.Something.Request(
			login: loginText,
			password: passwordText
		)
		interactor?.login(request: request)
	}
}
