//
//  LoginInteractor.swift
//  taskManager
//
//  Created by Давид Тоноян  on 22.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic {
	
	/// Функция логина, отправляет запрос валидации
	/// - Parameter request: Запрос с данными для логина
	func login(request: Login.Something.Request)
}

class LoginInteractor: LoginBusinessLogic {
	var presenter: LoginPresentationLogic?
	var worker: LoginWorker?

	// MARK: Do something

	func login(request: Login.Something.Request) {
		worker = LoginWorker()
		let result = worker?.login(login: request.login, password: request.password) ?? false
		let response = Login.Something.Response(isLoginSuccessed: result)
		presenter?.presentSomething(response: response)
	}
}
