//
//  LoginViewController.swift
//  taskManager
//
//  Created by Давид Тоноян  on 22.02.2023.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginDisplayLogic: AnyObject {
	
	/// Функция отображает ошибку
	func displayError()
	
	/// Функция процессинга при успешной валидации логина
	func processLogin()
}

final class LoginViewController: UIViewController, LoginDisplayLogic {
	
	// MARK: - Outlets
	
	@IBOutlet
	weak var loginTextField: UITextField!
	@IBOutlet
	weak var passwordTextField: UITextField!

	// MARK: - Parameters
	
	var interactor: ILoginBusinessLogic?
	var router: (NSObjectProtocol & ILoginRoutingLogic)?

	// MARK: View lifecycle

	override func viewDidLoad() {
		super.viewDidLoad()
	}

	// MARK: Do something
	
	func displayError() {
		router?.showError()
	}
	
	func processLogin() {
		router?.navigateToMainScreen()
	}

	@IBAction
	private func loginButtonTapped(_ sender: UIButton) {
		guard let loginText = loginTextField.text,
		      let passwordText = passwordTextField.text
		else {
			return
		}

		let request = LoginModel.Request(
			login: loginText,
			password: passwordText
		)
		interactor?.login(request: request)
	}
}
