name: Swift
on:
  pull_request:
    branches:
      - develop
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install SwiftGen
        run: brew install swiftgen
      - name: Clean SwiftLint
        run: rm "/usr/local/bin/swiftlint"
      - name: Install SwiftLint
        run: brew install swiftlint
      - name: Build
        run: xcodebuild -project "taskManager.xcodeproj" -scheme "taskManager" -destination "platform=iOS Simulator,name=iPhone 11"
      - name: Run tests
        run: xcodebuild test -project "taskManager.xcodeproj" -scheme "taskManager" -destination "platform=iOS Simulator,name=iPhone 11"
